suppressPackageStartupMessages({
  
  library(data.table)
  library(cmdstanr)
  library(rethinking)
  library(bayesplot)
  library(tarchetypes)
  library(ggplot2)
  library(targets)
  library(rbbt)
  library(rempsyc)
  library(readxl)
  
  library(brms)
  library(tidyr)
  library(dplyr)
  library(testthat)
  library(stantargets)
  library(bisonR)
  library(igraph)
  library(sjPlot)
  library(tidybayes)
  library(ggdist)
  library(geosphere)
  library(viridis)
  library(spatsoc)
  library(asnipe)
  library(patchwork)
  library(ggridges)
  library(irr)
  
  library(CCA)
  library(stats)
  library(tidyr)
  library(ggfortify)

})

print('Cleared packages')

